// File generated by FlutterFire CLI. // Arquivo gerado automaticamente – não editar manualmente
// ignore_for_file: type=lint // Ignora avisos de lint neste arquivo
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions; // FirebaseOptions - configurações do projeto
import 'package:flutter/foundation.dart'
    show
        defaultTargetPlatform,
        kIsWeb,
        TargetPlatform; // Detecta plataforma (Android, iOS, Web, etc.)

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Classe com configurações do Firebase por plataforma
  static FirebaseOptions get currentPlatform {
    // Getter: retorna opções da plataforma atual
    if (kIsWeb) {
      // Se for Web
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      ); // Web não configurado
    }
    switch (defaultTargetPlatform) {
      // Plataforma atual do app
      case TargetPlatform.android:
        return android; // Retorna configs Android
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); // iOS não configurado
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); // macOS não configurado
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); // Windows não configurado
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        ); // Linux não configurado
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        ); // Plataforma não suportada
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    // Configurações para Android
    apiKey:
        'AIzaSyAu8jeuDCrkyh8LpOmXaWWY2TS56xpSzvE', // Chave API do projeto Firebase
    appId: '1:431633472664:android:f7eb935059376779a184ed', // ID do app Android
    messagingSenderId: '431633472664', // ID para Firebase Cloud Messaging
    projectId: 'loja-virtual-8d7f7', // ID do projeto no Firebase
    storageBucket:
        'loja-virtual-8d7f7.firebasestorage.app', // Bucket do Firebase Storage
  );
}
